/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckIn {
  'time' : Time,
  'detail' : string,
  'photo' : [] | [string],
}
export interface CheckOut { 'time' : Time, 'detail' : string }
export interface DailyReport {
  'focus' : string,
  'focusRating' : number,
  'dedicationMetric' : Dedication,
  'strats' : string,
  'habit' : string,
  'healthRating' : number,
  'habitRating' : number,
  'flow' : string,
  'time' : Time,
  'dedication' : string,
  'flowRating' : number,
  'energyRating' : number,
  'dedicationRating' : number,
  'energy' : string,
  'health' : string,
}
export type Dedication = { 'sales' : null } |
  { 'technology' : null } |
  { 'leadership' : null };
export interface InputProfile { 'name' : string, 'dedication' : Dedication }
export interface KPIConfig {
  'activity2name' : string,
  'activity1weight' : number,
  'activity1active' : boolean,
  'activity4name' : string,
  'activity2weight' : number,
  'activity2active' : boolean,
  'activity3weight' : number,
  'activity1name' : string,
  'activity3active' : boolean,
  'activity4weight' : number,
  'activity3name' : string,
  'activity4active' : boolean,
  'activity5weight' : number,
  'activity5name' : string,
  'activity5active' : boolean,
}
export interface KPITally {
  'focus' : number,
  'habit' : number,
  'flow' : number,
  'dedication' : number,
  'energy' : number,
  'health' : number,
}
export interface PublicProfile { 'name' : string, 'dedication' : Dedication }
export interface Submission {
  'kpi' : KPITally,
  'report' : DailyReport,
  'relation' : number,
  'time' : Time,
  'user' : PublicProfile,
  'account' : string,
  'rating' : number,
  'reflection' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'dedication' : Dedication }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCheckIn' : ActorMethod<[string, [] | [string]], undefined>,
  'addCheckOut' : ActorMethod<[string], undefined>,
  'addSubmission' : ActorMethod<
    [DailyReport, string, string, string, number, number],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllCheckIns' : ActorMethod<[], Array<[Principal, Array<CheckIn>]>>,
  'getAllCheckOuts' : ActorMethod<[], Array<[Principal, Array<CheckOut>]>>,
  'getAllSubmissions' : ActorMethod<[], Array<[Principal, Array<Submission>]>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'getCheckOuts' : ActorMethod<[], Array<CheckOut>>,
  'getKPIConfig' : ActorMethod<[], KPIConfig>,
  'getPublicProfile' : ActorMethod<[], UserProfile>,
  'getSubmissionCount' : ActorMethod<[], bigint>,
  'getSubmissions' : ActorMethod<[], Array<Submission>>,
  'getUniqueDedications' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubmissions' : ActorMethod<[Principal], Array<Submission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsersWithRoles' : ActorMethod<[], Array<UserWithRole>>,
  'saveCallerUserProfile' : ActorMethod<[InputProfile], undefined>,
  'saveUserProfile' : ActorMethod<[InputProfile], undefined>,
  'updateKPIConfig' : ActorMethod<[KPIConfig], undefined>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];