/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Dedication = IDL.Variant({
  'sales' : IDL.Null,
  'technology' : IDL.Null,
  'leadership' : IDL.Null,
});
export const Time = IDL.Int;
export const DailyReport = IDL.Record({
  'focus' : IDL.Text,
  'focusRating' : IDL.Float64,
  'dedicationMetric' : Dedication,
  'strats' : IDL.Text,
  'habit' : IDL.Text,
  'healthRating' : IDL.Float64,
  'habitRating' : IDL.Float64,
  'flow' : IDL.Text,
  'time' : Time,
  'dedication' : IDL.Text,
  'flowRating' : IDL.Float64,
  'energyRating' : IDL.Float64,
  'dedicationRating' : IDL.Float64,
  'energy' : IDL.Text,
  'health' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CheckIn = IDL.Record({
  'time' : Time,
  'detail' : IDL.Text,
  'photo' : IDL.Opt(IDL.Text),
});
export const CheckOut = IDL.Record({ 'time' : Time, 'detail' : IDL.Text });
export const KPITally = IDL.Record({
  'focus' : IDL.Float64,
  'habit' : IDL.Float64,
  'flow' : IDL.Float64,
  'dedication' : IDL.Float64,
  'energy' : IDL.Float64,
  'health' : IDL.Float64,
});
export const PublicProfile = IDL.Record({
  'name' : IDL.Text,
  'dedication' : Dedication,
});
export const Submission = IDL.Record({
  'kpi' : KPITally,
  'report' : DailyReport,
  'relation' : IDL.Float64,
  'time' : Time,
  'user' : PublicProfile,
  'account' : IDL.Text,
  'rating' : IDL.Float64,
  'reflection' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'dedication' : Dedication,
});
export const KPIConfig = IDL.Record({
  'activity2name' : IDL.Text,
  'activity1weight' : IDL.Float64,
  'activity1active' : IDL.Bool,
  'activity4name' : IDL.Text,
  'activity2weight' : IDL.Float64,
  'activity2active' : IDL.Bool,
  'activity3weight' : IDL.Float64,
  'activity1name' : IDL.Text,
  'activity3active' : IDL.Bool,
  'activity4weight' : IDL.Float64,
  'activity3name' : IDL.Text,
  'activity4active' : IDL.Bool,
  'activity5weight' : IDL.Float64,
  'activity5name' : IDL.Text,
  'activity5active' : IDL.Bool,
});
export const UserWithRole = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});
export const InputProfile = IDL.Record({
  'name' : IDL.Text,
  'dedication' : Dedication,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addCheckOut' : IDL.Func([IDL.Text], [], []),
  'addSubmission' : IDL.Func(
      [DailyReport, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllCheckIns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CheckIn)))],
      ['query'],
    ),
  'getAllCheckOuts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CheckOut)))],
      ['query'],
    ),
  'getAllSubmissions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Submission)))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getCheckOuts' : IDL.Func([], [IDL.Vec(CheckOut)], ['query']),
  'getKPIConfig' : IDL.Func([], [KPIConfig], ['query']),
  'getPublicProfile' : IDL.Func([], [UserProfile], ['query']),
  'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getUniqueDedications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubmissions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
  'saveCallerUserProfile' : IDL.Func([InputProfile], [], []),
  'saveUserProfile' : IDL.Func([InputProfile], [], []),
  'updateKPIConfig' : IDL.Func([KPIConfig], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Dedication = IDL.Variant({
    'sales' : IDL.Null,
    'technology' : IDL.Null,
    'leadership' : IDL.Null,
  });
  const Time = IDL.Int;
  const DailyReport = IDL.Record({
    'focus' : IDL.Text,
    'focusRating' : IDL.Float64,
    'dedicationMetric' : Dedication,
    'strats' : IDL.Text,
    'habit' : IDL.Text,
    'healthRating' : IDL.Float64,
    'habitRating' : IDL.Float64,
    'flow' : IDL.Text,
    'time' : Time,
    'dedication' : IDL.Text,
    'flowRating' : IDL.Float64,
    'energyRating' : IDL.Float64,
    'dedicationRating' : IDL.Float64,
    'energy' : IDL.Text,
    'health' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CheckIn = IDL.Record({
    'time' : Time,
    'detail' : IDL.Text,
    'photo' : IDL.Opt(IDL.Text),
  });
  const CheckOut = IDL.Record({ 'time' : Time, 'detail' : IDL.Text });
  const KPITally = IDL.Record({
    'focus' : IDL.Float64,
    'habit' : IDL.Float64,
    'flow' : IDL.Float64,
    'dedication' : IDL.Float64,
    'energy' : IDL.Float64,
    'health' : IDL.Float64,
  });
  const PublicProfile = IDL.Record({
    'name' : IDL.Text,
    'dedication' : Dedication,
  });
  const Submission = IDL.Record({
    'kpi' : KPITally,
    'report' : DailyReport,
    'relation' : IDL.Float64,
    'time' : Time,
    'user' : PublicProfile,
    'account' : IDL.Text,
    'rating' : IDL.Float64,
    'reflection' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'dedication' : Dedication,
  });
  const KPIConfig = IDL.Record({
    'activity2name' : IDL.Text,
    'activity1weight' : IDL.Float64,
    'activity1active' : IDL.Bool,
    'activity4name' : IDL.Text,
    'activity2weight' : IDL.Float64,
    'activity2active' : IDL.Bool,
    'activity3weight' : IDL.Float64,
    'activity1name' : IDL.Text,
    'activity3active' : IDL.Bool,
    'activity4weight' : IDL.Float64,
    'activity3name' : IDL.Text,
    'activity4active' : IDL.Bool,
    'activity5weight' : IDL.Float64,
    'activity5name' : IDL.Text,
    'activity5active' : IDL.Bool,
  });
  const UserWithRole = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  const InputProfile = IDL.Record({
    'name' : IDL.Text,
    'dedication' : Dedication,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addCheckOut' : IDL.Func([IDL.Text], [], []),
    'addSubmission' : IDL.Func(
        [DailyReport, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllCheckIns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CheckIn)))],
        ['query'],
      ),
    'getAllCheckOuts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CheckOut)))],
        ['query'],
      ),
    'getAllSubmissions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Submission)))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getCheckOuts' : IDL.Func([], [IDL.Vec(CheckOut)], ['query']),
    'getKPIConfig' : IDL.Func([], [KPIConfig], ['query']),
    'getPublicProfile' : IDL.Func([], [UserProfile], ['query']),
    'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getUniqueDedications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubmissions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
    'saveCallerUserProfile' : IDL.Func([InputProfile], [], []),
    'saveUserProfile' : IDL.Func([InputProfile], [], []),
    'updateKPIConfig' : IDL.Func([KPIConfig], [], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };